### PR TITLE
feat: Update to Angular2 RC5

### PR DESCRIPTION
**Pull request by juanpmarin-infocorp**
#83

### CODE REVIEW

**Comment by rubyboy** [comment]
@juanpmarin-infocorp  thanks for the contribution.
Does the example project still work? I'd like to make sure the repository is consistent and all code works for the RC5 once dependencies are upgraded.
Thanks.

**Comment by juanpmarin-infocorp** [comment]
No, not works :c
Do you need to me fix it ?

**Comment by rubyboy** [comment]
Yes please. I can't really merge the PR and leave the project half baked.
Sorry, I would have done the upgrade myself (would love to) but I'm swamped and can only get to it in a week or two...

BTW, do you reckon we should upgrade the major version number after merging this PR? I think we should.

Thanks.

**Comment by juanpmarin-infocorp** [comment]
Yes, and mark the exports of MaterializeDirective as dreprecated

**Comment by rubyboy** [comment]
So with the new version you only need to bring in the module? Sweet!

**Comment by juanpmarin-infocorp** [comment]
Yeah :D

> For RC5, you can leave your components, directives and pipes in the directives and pipes properties of your @Component metadata. In fact, we automatically hoist (add) them to the NgModule to which they belong.

> This option is temporary for backward compatibility. It will be removed in the final release of Angular 2.0.

[https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html)

**Comment by juanpmarin-infocorp** [comment]
So, I will close this pull request and make other when running the demo

**Comment by rubyboy** [comment]
Thanks!

**Pull request closed without merging**
