### PR TITLE
262-datepicker-binding fix

### PR DESCRIPTION
**Pull request by criticalbh**
Sorry, I hope I am not too late for this one.

Fixes: https://github.com/InfomediaLtd/angular2-materialize/issues/262

### CODE REVIEW

**Comment by rubyboy** [comment]
@criticalbh thanks heaps for fixing. I've merged and it will build a new version promptly

**Comment by criticalbh** [comment]
Your welcome ;)

**Comment by ctytgat** [comment]
This seems to have broken something in the datepicker... When the datepicker is bound with a FormControl, the initial value is not displayed anymore. Works fine up to version 15.0.2.

I have:
`    <div class="input-field col s4">
        <input materialize="pickadate" [materializeParams]="[dateOptions]"
               id="activeFrom" type="text" formControlName="from"/>
        <label for="activeFrom">Actief van</label>
      </div>
`
and
`    this.form = fb.group({
      'from': new FormControl('06/07/2017'),
    });
`

**Comment by rubyboy** [comment]
PR merged: https://github.com/InfomediaLtd/angular2-materialize/pull/296

**Pull request merged**
