### PR TITLE
Date picker finished

### PR DESCRIPTION
**Pull request by criticalbh**

### CODE REVIEW

**Comment by rubyboy** [comment]
@criticalbh thanks heaps for the model binding example and the awesome datepicker support. You rock!

While testing I noticed the following doesn't work (datepicker field is not responsive):
```html
<label>Birthdate</label>
<input id="birthdate" materialize="pickadate" [materializeParams]="[{selectMonths: true, selectYears: 15}]" type="text" />
```
I've fixed that by updating the following line:
```js
        const datePickerPopUp = jQueryElement.siblings().first();
```
to:
```js
        const datePickerPopUp = jQueryElement.siblings(".picker").first();
```

See here: https://github.com/InfomediaLtd/angular2-materialize/commit/13d073eead749716b60936f15ef6348eae882cda

**Comment by criticalbh** [comment]
rubyboy, I have noticed my name is not in contributors list. Could you please guide me why?

**Comment by rubyboy** [comment]
@criticalbh you're absolutely right. I don't know why it doesn't show your name, though.
I've sent a question to Github support. Hopefully they can figure out the reason and help me amend it.

**Comment by rubyboy** [comment]
Hi @criticalbh, here's the answer I got from Github support:

> Commits are only added to your profile if they are authored by an email address that is associated with your GitHub account, as explained here:
> 
> https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/
> 
> It looks like your commits were authored by an address, admir@Sejos-MacBook-Pro.local, that is not associated with your GitHub account. You can check the commit author by adding .patch to the end of the commit URL, like this:
> 
> https://github.com/InfomediaLtd/angular2-materialize/commit/d13d74ec9dcf438acaf4673fddb6ac5af9a16952.patch
> 
> If you would like your future commits to be authored by a different email address that is already associated with your account, you will need to change your local Git configuration settings, as described here:
> 
> https://help.github.com/articles/setting-your-email-in-git/
> 
> Hope that helps!
> 
> Regards,
> Laura
> @lecoursen
> GitHub Support

**Comment by criticalbh** [comment]
HI @rubyboy . I didnt know where to text you so I decided to do it here. I have some idea for this project. Please when you find some time send me an email to admir_sabanovic@live.com or PM me on skype live:admir_sabanovic@live.com

**Pull request merged**
